# config/config.yaml
api_keys:
  groq_api_key: "${GROQ_API_KEY}"
  news_api_key: "${NEWS_API_KEY}"  # Get from newsapi.org
  alpha_vantage_key: "${ALPHA_VANTAGE_KEY}"  # Optional: for more data

google_sheets:
  spreadsheet_id: "${GOOGLE_SHEET_ID}"
  worksheet_name: "Daily_Stock_Picks"

# FTSE 100 stocks or custom list
uk_stocks:
  - "BARC.L"    # Barclays
  - "BP.L"      # BP
  - "BT-A.L"    # BT Group  
  - "LLOY.L"    # Lloyds Banking Group
  - "HSBA.L"    # HSBC Holdings
  - "VOD.L"     # Vodafone Group
  - "RIO.L"     # Rio Tinto
  - "SHEL.L"    # Shell
  - "AZN.L"     # AstraZeneca
  - "ULVR.L"    # Unilever
  - "GSK.L"     # GSK
  - "DGE.L"     # Diageo
  - "NG.L"      # National Grid
  - "REL.L"     # RELX
  - "LSEG.L"    # London Stock Exchange Group
  - "NWG.L"     # NatWest Group
  - "STAN.L"    # Standard Chartered
  - "PRU.L"     # Prudential
  - "IAG.L"     # International Airlines Group
  - "GLEN.L"    # Glencore

analysis_parameters:
  lookback_days: 30
  technical_indicators:
    - "RSI"
    - "MACD"
    - "Moving_Averages"
    - "Volume"
    - "Bollinger_Bands"
  
  sentiment_sources:
    - "news"
    - "social_media"
